name: Build Turkey Labeler EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify requirements
      run: |
        cat requirements.txt
        pip list

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed --hidden-import=PIL --hidden-import=PIL.Image --add-data "templates;templates" --add-data "ld_turkey_labeler.db;." --name "LD_Turkey_Labeler" app.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: LD_Turkey_Labeler
        path: dist/LD_Turkey_Labeler/**
